[Interface]
PrivateKey = DntEAaPm3OHiLsKdYwRaK4ANpBnX2yLnRR3ISnytaN4=
Address = 172.30.0.202/32
DNS = 8.8.8.8, 1.1.1.1

[Peer]
PublicKey = +1AETQwenOy6W+HROhXSckwvwPXcjIZTLhz5lI3kwww=
AllowedIPs = 0.0.0.0/0
Endpoint = usnj.wgn.qrvpn.com:11138
