[Interface]
PrivateKey = MCvOd8zICrZlCnwuG2DM+umtOPL+kL3JT38lA3lHsEU=
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = JOCzM1C/hQAqLa+ktsn5k/CdsEhnCy+tAtkyWTN/WW4=
Endpoint = rdseradmin.duckdns.org:51820
AllowedIPs = 10.0.0.0/24
PersistentKeepalive = 25
